### PR TITLE
min max functions

### PR DESCRIPTION
**Pull request by 2mol**
I couldn't figure out how to run the tests unfortunately, but once I do I will add some.

### CODE REVIEW

**Comment by justinmimbs** [comment]
Thanks! Oh yes, the tests: I wrote the tests for 0.19 before elm-test was upgraded, so you can run the tests in the REPL like this:

```elm
import Shim
import Tests
Shim.run Tests.suite
```

If you get back `( <number of tests>, [] )`, then all tests passed. The second part of the result is the list of failures.

**Comment by justinmimbs** [comment]
Would you mind if we implemented them like this, to avoid calling `compare`?

```elm
min ((RD a) as d1) ((RD b) as d2) =
    if a < b then
        d1

    else
        d2
```

I think it would be nice if `min`, `max`, and `clamp` didn't call another function or allocate a new `Date`. I see that `clamp` currently does both, so I'll update it in the style above so it does neither.

Thanks!

**Comment by 2mol** [comment]
absolutely, I agree that it's clearer!

**Comment by justinmimbs** [comment]
Sweet! Did you want to add some tests before I merge?

**Comment by 2mol** [comment]
Yup, I thought I'd do it right right away :) Should have time later today

**Pull request merged**
